version: '3.4'

services:
  cipher_safe_bank:
    image: ${DOCKER_REGISTRY-}cipher_safe_bank
    build:
      context: .
      dockerfile: Cipher_Safe_Bank/Dockerfile
    ports:
    - 26002:80
    volumes:
      - /root/certificate.p12:/app/certificate.p12
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=@Ninh1209
      - ASPNETCORE_Kestrel__Certificates__Default__Path=certificate.p12
